### ISSUE TITLE
Player not maintaining proper state in edge case

### ISSUE THREAD

**Issue by mnewberg** [mnewberg/whitmanc.github.io#2]
@whitmanc I just found the following issue. Here's steps to replicate (you can test it out live on my site here: http://pulsestaging.s3-website-us-east-1.amazonaws.com/
1. Click stream A, starts playing, then pause it
2. Click logo to go back home
3. Click stream B, player is still set to stream A

Note this only happens if you navigate back home after pausing, not if you're already playing a station... there should be no case in which you would be able to get another venue's stream played on a particular venue page.

**Comment by whitman** [comment]
@mnewberg got it

**Comment by whitmanc** [comment]
Resolved, please confirm @mnewberg

**Comment by mnewberg** [comment]
@whitmanc works, thanks
