### ISSUE TITLE
Show loading indicator if stream is loading 

### ISSUE THREAD

**Issue by whitmanc** [mnewberg/whitmanc.github.io#5]
@mnewberg 
Put in a loading indicator for when a stream is loading. Thought this would be good for the ux.

Can be tested by clicking a venue play button on the venue list (home) page. A loading indicator should show on the fixed footer toolbar for radio controls as an overlay over the venue thumbnail. 

Let me know if it should be removed.

**Comment by mnewberg** [comment]
@whitmanc perfect thanks!
